services:
  portainer:
    image: portainer/portainer
    ports:
    - 9000:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /opt/portainer:/data
    restart: unless-stopped
version: '3'    

